version: '3.0'
networks:
  guacnetwork_compose:
    driver: overlay
# services
services:
  # guacd
  guacd:
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
    deploy:
      restart_policy:
        condition: any

  # postgres
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'Welcome!12345'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4-buster
    networks:
      guacnetwork_compose:
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z
    deploy:
      restart_policy:
        condition: any
        
  # guacamole
  guacamole:
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'Welcome!12345'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    networks:
      guacnetwork_compose:
    ports:
    - 8080/tcp
    deploy:
      restart_policy:
        condition: any

  nginx:
   image: nginx
   volumes:
   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./nginx/mysite.template:/etc/nginx/conf.d/default.conf:ro
   ports:
   - 8443:443
   networks:
     guacnetwork_compose:
   command: /bin/bash -c "nginx -g 'daemon off;'"
   deploy:
     restart_policy:
       condition: any

  cloudflare:
   image: karthick1808/cloudflare:latest
   networks:
     guacnetwork_compose:
   deploy:
     restart_policy:
       condition: any
